### ISSUE TITLE
ETH connect does only work with Arduino core v1.0.6

### ISSUE THREAD

**Issue by AndreasMainz** [khoih-prog/WebServer_WT32_ETH01#1]
### Describe the bug

The WT32-ETH01 board can not connect to ethernet using the new core v2.0.0, only with:
WebServer_WT32_ETH01 v1.3.0 for core v1.0.6-

### Steps to Reproduce
SW part for connect:

  ETH.begin(ETH_PHY_ADDR, ETH_PHY_POWER);
  ETH.config(myIP, myGW, mySN, myDNS);
  WiFi.onEvent(WiFiEvent);
  while (!eth_connected) { // Es gibt oft Probleme mit der Verbindung
    Serial.print("*");
    delay(100);
  }

### Expected behavior

****************************************ETH MAC: 7C:87:CE:44:B0:CB, IPv4: 192.168.1.112, FULL_DUPLEX, 100Mbps
Connection successfull

### Actual behavior on core v2.0.0

****************************************.... endless

### Information

Please ensure to specify the following:

* Arduino IDE version e.g. 1.8.9
* ESP32 v1.06
* Win10

* Simplest possible steps to reproduce
* switch between the arduino kernels.  ESP32 v1.06 good <-> v2.0.0 bad
*

**Comment by khoih-prog** [comment]
Thanks for your usage of the library.

Did you read [**Important notes**](https://github.com/khoih-prog/WebServer_WT32_ETH01#important-notes) and be sure to use the [**v1.3.0 to be compatible either with breaking ESP32 core v2.0.0+ or core v1.0.6-**](https://github.com/khoih-prog/WebServer_WT32_ETH01/releases/tag/v1.3.0) ?

---

#### Releases v1.3.0

##### Warning: Can be used for either EP32 core v2.0.0+ or v1.0.6-. Default is v2.0.0+ now

1. Making compatible either with breaking core v2.0.0+ or core v1.0.6-
2. Renew examples

**Comment by khoih-prog** [comment]
Have a look at examples first, then you must change your code to

```
  ETH.begin(ETH_PHY_ADDR, ETH_PHY_POWER);

  // Static IP, leave without this line to get IP via DHCP
  //bool config(IPAddress local_ip, IPAddress gateway, IPAddress subnet, IPAddress dns1 = 0, IPAddress dns2 = 0);
  ETH.config(myIP, myGW, mySN, myDNS);

  WT32_ETH01_onEvent();

  WT32_ETH01_waitForConnect();
```

Core v2.0.0 breaks almost all code written for v1.0.6-, such as yours.

**Comment by AndreasMainz** [comment]
Hello,

i updates to the newest Arduino-core and used original 
WebServer Example only modifiing my ip adress like this:
IPAddress myIP(192, 168, 1, 232);

Serial monitor shows:
14:41:31.797 -> Starting WebServer on ESP32_DEV with ETH_PHY_LAN8720
14:41:31.797 -> WebServer_WT32_ETH01 v1.3.0 for core v2.0.0+
 BUT

still NO connect!

**Comment by khoih-prog** [comment]
Sorry, I'm just testing again and there is no issue with the library

```

Starting WebClientRepeating on ESP32_DEV with ETH_PHY_LAN8720
WebServer_WT32_ETH01 v1.3.0 for core v2.0.0+
ETH MAC: A8:03:2A:A1:61:73, IPv4: 192.168.2.95
FULL_DUPLEX, 100Mbps

Connecting...
HTTP/1.1 200 OK
Server: nginx/1.4.2
Date: Fri, 05 Nov 2021 17:04:47 GMT
Content-Type: text/plain
Content-Length: 2263
Last-Modified: Wed, 02 Oct 2013 13:46:47 GMT
Connection: close
Vary: Accept-Encoding
ETag: "524c23c7-8d7"
Accept-Ranges: bytes


           `:;;;,`                      .:;;:.           
        .;;;;;;;;;;;`                :;;;;;;;;;;:     TM 
      `;;;;;;;;;;;;;;;`            :;;;;;;;;;;;;;;;      
     :;;;;;;;;;;;;;;;;;;         `;;;;;;;;;;;;;;;;;;     
    ;;;;;;;;;;;;;;;;;;;;;       .;;;;;;;;;;;;;;;;;;;;    
   ;;;;;;;;:`   `;;;;;;;;;     ,;;;;;;;;.`   .;;;;;;;;   
  .;;;;;;,         :;;;;;;;   .;;;;;;;          ;;;;;;;  
  ;;;;;;             ;;;;;;;  ;;;;;;,            ;;;;;;. 
 ,;;;;;               ;;;;;;.;;;;;;`              ;;;;;; 
 ;;;;;.                ;;;;;;;;;;;`      ```       ;;;;;`
 ;;;;;                  ;;;;;;;;;,       ;;;       .;;;;;
`;;;;:                  `;;;;;;;;        ;;;        ;;;;;
,;;;;`    `,,,,,,,,      ;;;;;;;      .,,;;;,,,     ;;;;;
:;;;;`    .;;;;;;;;       ;;;;;,      :;;;;;;;;     ;;;;;
:;;;;`    .;;;;;;;;      `;;;;;;      :;;;;;;;;     ;;;;;
.;;;;.                   ;;;;;;;.        ;;;        ;;;;;
 ;;;;;                  ;;;;;;;;;        ;;;        ;;;;;
 ;;;;;                 .;;;;;;;;;;       ;;;       ;;;;;,
 ;;;;;;               `;;;;;;;;;;;;                ;;;;; 
 `;;;;;,             .;;;;;; ;;;;;;;              ;;;;;; 
  ;;;;;;:           :;;;;;;.  ;;;;;;;            ;;;;;;  
   ;;;;;;;`       .;;;;;;;,    ;;;;;;;;        ;;;;;;;:  
    ;;;;;;;;;:,:;;;;;;;;;:      ;;;;;;;;;;:,;;;;;;;;;;   
    `;;;;;;;;;;;;;;;;;;;.        ;;;;;;;;;;;;;;;;;;;;    
      ;;;;;;;;;;;;;;;;;           :;;;;;;;;;;;;;;;;:     
       ,;;;;;;;;;;;;;,              ;;;;;;;;;;;;;;       
         .;;;;;;;;;`                  ,;;;;;;;;:         
                                                         
                                                         
                                                         
                                                         
    ;;;   ;;;;;`  ;;;;:  .;;  ;; ,;;;;;, ;;. `;,  ;;;;   
    ;;;   ;;:;;;  ;;;;;; .;;  ;; ,;;;;;: ;;; `;, ;;;:;;  
   ,;:;   ;;  ;;  ;;  ;; .;;  ;;   ,;,   ;;;,`;, ;;  ;;  
   ;; ;:  ;;  ;;  ;;  ;; .;;  ;;   ,;,   ;;;;`;, ;;  ;;. 
   ;: ;;  ;;;;;:  ;;  ;; .;;  ;;   ,;,   ;;`;;;, ;;  ;;` 
  ,;;;;;  ;;`;;   ;;  ;; .;;  ;;   ,;,   ;; ;;;, ;;  ;;  
  ;;  ,;, ;; .;;  ;;;;;:  ;;;;;: ,;;;;;: ;;  ;;, ;;;;;;  
  ;;   ;; ;;  ;;` ;;;;.   `;;;:  ,;;;;;, ;;  ;;,  ;;;;   
```

Try to use DHCP IP by

```
  // Static IP, leave without this line to get IP via DHCP
  //bool config(IPAddress local_ip, IPAddress gateway, IPAddress subnet, IPAddress dns1 = 0, IPAddress dns2 = 0);
  //ETH.config(myIP, myGW, mySN, myDNS);
```

or check to use correct static IP/ GW / SN, e.g.

```
IPAddress myIP(192, 168, 1, 232);
IPAddress myGW(192, 168, 1, 1);
IPAddress mySN(255, 255, 255, 0);
```

I'm sorry I don't have time to deal with your issue anymore **as this is not issue / bug of this library**. Try asking for help in Arduino Forum, etc

Good Luck
