### ISSUE TITLE
Not really having an issue I just need help with something

### ISSUE THREAD

**Issue by PrinceSalmon** [khoih-prog/WebServer_WT32_ETH01#15]
Hey do you have a discord by any chance? Im currently doing a project that will probably use your libraries, i just need someone to reach out too as im using the WT32-ETH01

**Comment by khoih-prog** [comment]
Sorry I don't do that kind of personal project support and please don't rely on anybody else but **you and your team**.
Just post any real issue here or anywhere, such as other Forum, hopefully to get in-time help.

I'm closing this as not a library's issue

Good Luck,
