### ISSUE TITLE
Example Sketches Work Unreliably

### ISSUE THREAD

**Issue by lynestelles** [khoih-prog/WebServer_WT32_ETH01#2]
### Describe the bug

Sometimes, after uploading the original sample sketch, it works fine/as intended. Sometimes, It doesnt. Instead of showing the ip address on the serial monitor, it will read the following:

Start Async_HelloServer2 on WT32-ETH01 with ETH_PHY_LAN8720
AsyncWebServer_WT32_ETH01 v1.3.0 for core v2.0.0+
ETH Disconnected
ETH Connected
ETH Disconnected
ETH Connected
...and so on.

Sometimes, it will show on the serial port ETH Connected, but never return from WT32_ETH01_waitForConnect();. Instead, it will occasionally print out:  "E (87081) esp.emac: emac_esp32_transmit(234): insufficient TX buffer size" on the serial port.

I purchased two WT32-ETH01 from AliExpress. This issue occurs on both of them.

I powered/ uploaded the sketch through a seperate ESP32 (with EN grounded and TX/RX lines to the WT32-ETH01). Assuming this was a power issue, I powered the WT32-ETH01 with 5V directly, and the issue persisted. 

This issue occurs with both Static IP address and letting the DHCP handle it.

### Steps to Reproduce

Upload example sketch. Have the ethernet cable connected before powering up.

### Expected behavior

Async_HelloServer2.ino sketch uploaded and have the WT32 connect to the local network and print out the IP address.

### Actual behavior

Sometimes connects and works properly. If you restart it a few times, it will just show ETH connected/Disconnected, but never print out the IP address

### Screenshots

Added below.

### Information

Arduino 1.8.16
Windows 11
ESP Core V2.0

![troubleshoowingAsyncWebserver](https://user-images.githubusercontent.com/45347701/140582043-1a83d001-fed4-4702-b2af-787ab5c0d76d.jpg)

Sample code below:

`/****************************************************************************************************************************
  Async_HelloServer2.ino - Dead simple AsyncWebServer for WT32_ETH01
  
  For LAN8720 Ethernet in WT32_ETH01 (ESP32 + LAN8720)

  AsyncWebServer_WT32_ETH01 is a library for the Ethernet LAN8720 in WT32_ETH01 to run AsyncWebServer

  Based on and modified from ESPAsyncWebServer (https://github.com/me-no-dev/ESPAsyncWebServer)
  Built by Khoi Hoang https://github.com/khoih-prog/AsyncWebServer_WT32_ETH01
  Licensed under GPLv3 license 
 *****************************************************************************************************************************/

#if !( defined(ESP32) )
  #error This code is designed for WT32_ETH01 to run on ESP32 platform! Please check your Tools->Board setting.
#endif

// Uncomment to use ESP32 core v1.0.6-
//#define USING_CORE_ESP32_CORE_V200_PLUS     false

#include <Arduino.h>

#define _ASYNC_WEBSERVER_LOGLEVEL_       4

// Select the IP address according to your local network
IPAddress myIP(192, 168, 2, 232);
IPAddress myGW(192, 168, 2, 1);
IPAddress mySN(255, 255, 255, 0);

// Google DNS Server IP
IPAddress myDNS(8, 8, 8, 8);

#include <AsyncTCP.h>

#include <AsyncWebServer_WT32_ETH01.h>

AsyncWebServer    server(80);

void handleRoot(AsyncWebServerRequest *request)
{
  request->send(200, "text/plain", String("Hello from Async_HelloServer2 on ") + BOARD_NAME );
}

void handleNotFound(AsyncWebServerRequest *request)
{
  String message = "File Not Found\n\n";

  message += "URI: ";
  //message += server.uri();
  message += request->url();
  message += "\nMethod: ";
  message += (request->method() == HTTP_GET) ? "GET" : "POST";
  message += "\nArguments: ";
  message += request->args();
  message += "\n";

  for (uint8_t i = 0; i < request->args(); i++)
  {
    message += " " + request->argName(i) + ": " + request->arg(i) + "\n";
  }

  request->send(404, "text/plain", message);
}

void setup(void)
{
  Serial.begin(115200);
  while (!Serial);

  delay(200);

  Serial.print(F("\nStart Async_HelloServer2 on ")); Serial.print(BOARD_NAME);
  Serial.print(F(" with ")); Serial.println(SHIELD_TYPE);
  Serial.println(ASYNC_WEBSERVER_WT32_ETH01_VERSION);

  //bool begin(uint8_t phy_addr=ETH_PHY_ADDR, int power=ETH_PHY_POWER, int mdc=ETH_PHY_MDC, int mdio=ETH_PHY_MDIO, 
  //           eth_phy_type_t type=ETH_PHY_TYPE, eth_clock_mode_t clk_mode=ETH_CLK_MODE);
  //ETH.begin(ETH_PHY_ADDR, ETH_PHY_POWER, ETH_PHY_MDC, ETH_PHY_MDIO, ETH_PHY_TYPE, ETH_CLK_MODE);
  ETH.begin(ETH_PHY_ADDR, ETH_PHY_POWER);

  // Static IP, leave without this line to get IP via DHCP
  //bool config(IPAddress local_ip, IPAddress gateway, IPAddress subnet, IPAddress dns1 = 0, IPAddress dns2 = 0);
//  ETH.config(myIP, myGW, mySN, myDNS);

  WT32_ETH01_onEvent();

  WT32_ETH01_waitForConnect();

  server.on("/", HTTP_GET, [](AsyncWebServerRequest * request)
  {
    handleRoot(request);
  });

  server.on("/inline", [](AsyncWebServerRequest * request)
  {
    request->send(200, "text/plain", "This works as well");
  });

  server.on("/gif", [](AsyncWebServerRequest * request) 
  {
    static const uint8_t gif[] = 
    {
      0x47, 0x49, 0x46, 0x38, 0x37, 0x61, 0x10, 0x00, 0x10, 0x00, 0x80, 0x01,
      0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x2c, 0x00, 0x00, 0x00, 0x00,
      0x10, 0x00, 0x10, 0x00, 0x00, 0x02, 0x19, 0x8c, 0x8f, 0xa9, 0xcb, 0x9d,
      0x00, 0x5f, 0x74, 0xb4, 0x56, 0xb0, 0xb0, 0xd2, 0xf2, 0x35, 0x1e, 0x4c,
      0x0c, 0x24, 0x5a, 0xe6, 0x89, 0xa6, 0x4d, 0x01, 0x00, 0x3b
    };
    
    char gif_colored[sizeof(gif)];

    memcpy(gif_colored, gif, sizeof(gif));

    // Set the background to a random set of colors
    gif_colored[16] = millis() % 256;
    gif_colored[17] = millis() % 256;
    gif_colored[18] = millis() % 256;

    request->send(200, (char *) "image/gif", gif_colored);
  });

  server.onNotFound(handleNotFound);

  server.begin();

  Serial.print("HTTP EthernetWebServer started @ IP : ");
  Serial.println(ETH.localIP());
}

void loop(void)
{
}`

**Comment by khoih-prog** [comment]
> Sometimes connects and works properly. If you restart it a few times, it will just show ETH connected/Disconnected, but never print out the IP address

The board somehow crashed and reset itself randomly.

Try with Windows 10 or Ubuntu, different router / network, etc. and see if any better?

I couldn't duplicate the issue and suspect this is **board-related.**

The **erratic** behaviour certainly creates not by the library, but your boards (**power, bad component, solder, residue, etc**.) and I have to close the issue as there is no way now to debug or know what's happening there.

Try to post the issue on Arduino or ESP32 forum and hope someone having the similar issue / solution.

Good Luck,

**Comment by lynestelles** [comment]
Follow up: Purchased and tried WT32 from different vendor. No issues, worked as intended.
