### ISSUE TITLE
send gzip html

### ISSUE THREAD

**Issue by SurfGargano** [khoih-prog/WebServer_WT32_ETH01#4]
I send the html via
  server.send_P(200, "text/html", (const char*) tfs____web_pages_h_index_html , sizeof(tfs____web_pages_h_index_html)); 

How can I add 'Content-Encoding: gzip' and  send a gzip html ?

best regards
Werner

**Comment by khoih-prog** [comment]
This library is just a simple `wrapper` around the [**ESP32 WebServer** library](https://github.com/espressif/arduino-esp32/tree/master/libraries/WebServer) and you can get more info about how to use for more complex use-cases there.

Basically, have a look at [**ESP32_FS_EthernetWebServer** example](https://github.com/khoih-prog/WebServer_WT32_ETH01/tree/main/examples/ESP32_FS_EthernetWebServer) and find out how to send `gzip` file. More info can be found in [**ESP32_FS_EthernetWebServer.ino#L142-L197**](https://github.com/khoih-prog/WebServer_WT32_ETH01/blob/main/examples/ESP32_FS_EthernetWebServer/ESP32_FS_EthernetWebServer.ino#L142-L197) and [**mimetable.h**](https://github.com/khoih-prog/EthernetWebServer/blob/master/src/detail/mimetable.h).

If you still have issue, post `request for help` on **Arduino or ESP32** forum. You can also `Google search` and find out how to do.

As this no-issue needs some **basic HTML knowledge** and has nothing to do with this library, I'm closing the issue now.

Good Luck,
